# AUTO-GENERATED by radar.py from discovered evidence. Do not edit.
"""Boards the radar promoted because they returned Canadian student roles.

Curated boards stay in companies.py. This file is rewritten at the end of a
normal run or ``--seed``, never by ``--check``.
"""

AUTO_COMPANIES: list[dict] = [
]
