# AUTO-GENERATED by radar.py from discovered evidence. Do not edit.
"""Boards the radar promoted because they returned Canadian student roles.

Curated boards stay in companies.py. This file is rewritten at the end of a
normal run or ``--seed``, never by ``--check``.
"""

AUTO_COMPANIES: list[dict] = [
    {'name': 'Acceldata', 'platform': 'lever', 'token': 'acceldata', 'ai_native': False},
    {'name': 'AECOM', 'platform': 'smartrecruiters', 'token': 'AECOM2', 'ai_native': False},
    {'name': 'Alexion', 'platform': 'workday', 'token': 'https://astrazeneca.wd3.myworkdayjobs.com/wday/cxs/astrazeneca/alexion/jobs', 'ai_native': False},
    {'name': 'Altera', 'platform': 'workday', 'token': 'https://altera.wd1.myworkdayjobs.com/wday/cxs/altera/altera/jobs', 'ai_native': False},
    {'name': 'Autodesk', 'platform': 'workday', 'token': 'https://autodesk.wd1.myworkdayjobs.com/wday/cxs/autodesk/uni/jobs', 'ai_native': False},
    {'name': 'Bank of Montreal', 'platform': 'workday', 'token': 'https://bmo.wd3.myworkdayjobs.com/wday/cxs/bmo/Campus/jobs', 'ai_native': False},
    {'name': 'BDO Canada', 'platform': 'workday', 'token': 'https://bdo.wd3.myworkdayjobs.com/wday/cxs/bdo/BDO/jobs', 'ai_native': False},
    {'name': 'Bird Construction', 'platform': 'workday', 'token': 'https://bird.wd3.myworkdayjobs.com/wday/cxs/bird/BirdConstructionCareers/jobs', 'ai_native': False},
    {'name': 'Bree', 'platform': 'ashby', 'token': 'bree', 'ai_native': False},
    {'name': 'Brookfield', 'platform': 'workday', 'token': 'https://brookfield.wd5.myworkdayjobs.com/wday/cxs/brookfield/brookfieldprivate/jobs', 'ai_native': False},
    {'name': 'Canadian Tire', 'platform': 'workday', 'token': 'https://canadiantirecorporation.wd3.myworkdayjobs.com/wday/cxs/canadiantirecorporation/Enterprise_External_Careers_Site/jobs', 'ai_native': False},
    {'name': 'Capital One', 'platform': 'workday', 'token': 'https://capitalone.wd12.myworkdayjobs.com/wday/cxs/capitalone/Capital_One/jobs', 'ai_native': False},
    {'name': 'Cresta', 'platform': 'greenhouse', 'token': 'cresta', 'ai_native': False},
    {'name': 'DoorDash', 'platform': 'greenhouse', 'token': 'doordashcanada', 'ai_native': False},
    {'name': 'Equitable Bank', 'platform': 'lever', 'token': 'eqbank', 'ai_native': False},
    {'name': 'Farm Credit Canada', 'platform': 'workday', 'token': 'https://fccfac.wd3.myworkdayjobs.com/wday/cxs/fccfac/careers-carrieres/jobs', 'ai_native': False},
    {'name': 'Foresters Financial', 'platform': 'workday', 'token': 'https://foresters.wd3.myworkdayjobs.com/wday/cxs/foresters/ForestersFinancialCareers/jobs', 'ai_native': False},
    {'name': 'General Motors', 'platform': 'workday', 'token': 'https://generalmotors.wd5.myworkdayjobs.com/wday/cxs/generalmotors/Careers_GM/jobs', 'ai_native': False},
    {'name': 'Georgian Partners Growth', 'platform': 'ashby', 'token': 'georgian', 'ai_native': False},
    {'name': 'Hitachi Energy', 'platform': 'workday', 'token': 'https://hitachi.wd1.myworkdayjobs.com/wday/cxs/hitachi/hitachi/jobs', 'ai_native': False},
    {'name': 'Human Computer Lab', 'platform': 'ashby', 'token': 'human-computer-lab', 'ai_native': False},
    {'name': 'Intact', 'platform': 'workday', 'token': 'https://intactfc.wd3.myworkdayjobs.com/wday/cxs/intactfc/intactfc/jobs', 'ai_native': False},
    {'name': 'Lumentum', 'platform': 'workday', 'token': 'https://lumentum.wd5.myworkdayjobs.com/wday/cxs/lumentum/LITE/jobs', 'ai_native': False},
    {'name': 'Marvell', 'platform': 'workday', 'token': 'https://marvell.wd1.myworkdayjobs.com/wday/cxs/marvell/MarvellCareers/jobs', 'ai_native': False},
    {'name': 'Marvell', 'platform': 'workday', 'token': 'https://marvell.wd1.myworkdayjobs.com/wday/cxs/marvell/MarvellCareers2/jobs', 'ai_native': False},
    {'name': 'Nuclear Promise X', 'platform': 'ashby', 'token': 'NPX', 'ai_native': False},
    {'name': 'Procter & Gamble', 'platform': 'workday', 'token': 'https://pg.wd5.myworkdayjobs.com/wday/cxs/pg/1000/jobs', 'ai_native': False},
    {'name': 'Rocket Lab USA', 'platform': 'greenhouse', 'token': 'rocketlab', 'ai_native': False},
    {'name': 'Rockwell Automation', 'platform': 'workday', 'token': 'https://rockwellautomation.wd1.myworkdayjobs.com/wday/cxs/rockwellautomation/External-Rockwell-Automation-Early-Careers/jobs', 'ai_native': False},
    {'name': 'Rockwell Automation', 'platform': 'workday', 'token': 'https://rockwellautomation.wd1.myworkdayjobs.com/wday/cxs/rockwellautomation/External_Rockwell_Automation/jobs', 'ai_native': False},
    {'name': 'Royal Bank of Canada', 'platform': 'workday', 'token': 'https://rbc.wd3.myworkdayjobs.com/wday/cxs/rbc/ExternalPrivatePostingStudents/jobs', 'ai_native': False},
    {'name': 'Semtech', 'platform': 'workday', 'token': 'https://semtech.wd1.myworkdayjobs.com/wday/cxs/semtech/SemtechCareers/jobs', 'ai_native': False},
    {'name': 'ShyftLabs', 'platform': 'lever', 'token': 'shyftlabs', 'ai_native': False},
    {'name': 'Solink', 'platform': 'ashby', 'token': 'solink', 'ai_native': False},
    {'name': 'SOTI', 'platform': 'workday', 'token': 'https://soti.wd3.myworkdayjobs.com/wday/cxs/soti/SOTI-Next-Gen/jobs', 'ai_native': False},
    {'name': 'Sun Life', 'platform': 'workday', 'token': 'https://sunlife.wd3.myworkdayjobs.com/wday/cxs/sunlife/Campus/jobs', 'ai_native': False},
    {'name': 'Tenstorrent', 'platform': 'greenhouse', 'token': 'tenstorrentuniversity', 'ai_native': False},
    {'name': 'The Home Depot', 'platform': 'workday', 'token': 'https://homedepot.wd5.myworkdayjobs.com/wday/cxs/homedepot/CareerDepotCanada/jobs', 'ai_native': False},
    {'name': 'Yotta Labs', 'platform': 'ashby', 'token': 'yotta', 'ai_native': False},
    {'name': 'Zip', 'platform': 'ashby', 'token': 'zip', 'ai_native': False},
]
